### PR TITLE
Pull request for Lesson03/Session03 for mathewcm

### PR DESCRIPTION
**Pull request by mathewcmartin**

### CODE REVIEW

**Comment by HarryMaher** [comment]
Oh no, it looks like there are conflicts because you've added files from other students' folders? Any ideas on how to fix this @PythonCHB or @hosungs ?

**Comment by mathewcmartin** [comment]
@HarryMaher I did a 'git reset --hard 573632c'  and reverted back to previous commit. I can now do a git pull and see the upstream changes.

**Comment by HarryMaher** [comment]
The issue is that there are "182 files changed" including ones that aren't in your student directory. Which isn't ideal cause we don't want students accidentally changing each others' files. No big deal, but I think we'll have to remove this PR and figure out what to do from there.

**Comment by mathewcmartin** [comment]
Sounds good! If someone wants to change my files I'm cool with it. As long
they work better after. Pretty sure no one wants me changing theirs though.
LOL

M

**Pull request closed without merging**
